print_next_observance:
  name: Print Next Observance
  description: Fetches the next observance from Is Around and prints the attendance PDF.
  fields: 
    printer_entity:
      name: Printer Entity
      description: The entity ID of the printer to use.
      required: false
      selector:
        entity:
          domain: "sensor"
          integration: "ipp_printer_service"
    copies:
      name: Copies
      description: Number of copies to print.
      required: false
      default: 1
      selector:
        number:
          min: 1
          max: 5
          mode: box
      
test_connection:
  name: Test Connection
  description: Tests the connection to the Is Around API.
  fields: 
    app_url: 
      name: App URL
      description: The URL of the Is Around app to connect to.
      required: false
      selector:
        text:
          type: url
    username: 
      name: Username
      description: The username to use for authentication.
      required: false
      selector:
        text:
          type: text
    password: 
      name: Password
      description: The password to use for authentication.
      required: false
      selector:
        text:
          type: password

send_attendance:
 name: Send Attendance Push
 description: Initiates the attendance push message flow for candidates at the Is-Around server.

discard_session:
  name: Discard Session
  description: "Discards the current session cookies for the Is Around Connector. A new session will be established on the next request."
  fields: {}

build_session:
  name: Build Session
  description: "Builds a new session by re-authenticating with the stored credentials."
  fields: {}
